import type { RequestStatus } from "../types";

export interface SeedUser {
  key: string;
  name: string;
  phone: string;
  email: string;
  profilePhoto: string;
  city: string;
  locality: string;
  kycStatus: "not_started" | "pending" | "verified" | "failed";
  lenderRating: number;
  renterRating: number;
  isPhoneVerified: boolean;
  roleTags: string[];
}

export interface SeedListing {
  title: string;
  category: string;
  subcategory: string;
  description: string;
  condition: string;
  replacementValue: number;
  rentPrice: number;
  rentUnit: "day" | "week" | "month";
  depositAmount: number;
  deliveryAvailable: boolean;
  rules: string[];
  accessories: string[];
  specifications?: Record<string, string | number>;
  photos?: string[];
  imageQuery?: string;
}

export const seedUsers: SeedUser[] = [
  {
    key: "admin_ananya",
    name: "Ananya Rao",
    phone: "9876501001",
    email: "ananya.admin@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=47",
    city: "Bengaluru",
    locality: "Indiranagar",
    kycStatus: "verified",
    lenderRating: 4.9,
    renterRating: 4.8,
    isPhoneVerified: true,
    roleTags: ["admin", "hybrid"],
  },
  {
    key: "lender_vikram",
    name: "Vikram Nair",
    phone: "9876501002",
    email: "vikram.lender@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=11",
    city: "Bengaluru",
    locality: "HSR Layout",
    kycStatus: "verified",
    lenderRating: 4.8,
    renterRating: 4.5,
    isPhoneVerified: true,
    roleTags: ["lender"],
  },
  {
    key: "renter_neha",
    name: "Neha Sharma",
    phone: "9876501003",
    email: "neha.renter@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=5",
    city: "Bengaluru",
    locality: "Koramangala",
    kycStatus: "pending",
    lenderRating: 4.2,
    renterRating: 4.7,
    isPhoneVerified: true,
    roleTags: ["renter"],
  },
  {
    key: "hybrid_arjun",
    name: "Arjun Mehta",
    phone: "9876501004",
    email: "arjun.hybrid@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=33",
    city: "Mumbai",
    locality: "Powai",
    kycStatus: "verified",
    lenderRating: 4.7,
    renterRating: 4.6,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
  {
    key: "lender_sara",
    name: "Sara Khan",
    phone: "9876501005",
    email: "sara.lender@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=9",
    city: "Mumbai",
    locality: "Andheri",
    kycStatus: "verified",
    lenderRating: 4.8,
    renterRating: 4.4,
    isPhoneVerified: true,
    roleTags: ["lender"],
  },
  {
    key: "hybrid_rohan",
    name: "Rohan Kapoor",
    phone: "9876501006",
    email: "rohan.hybrid@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=13",
    city: "Delhi",
    locality: "Saket",
    kycStatus: "pending",
    lenderRating: 4.5,
    renterRating: 4.5,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
  {
    key: "lender_pooja",
    name: "Pooja Iyer",
    phone: "9876501007",
    email: "pooja.lender@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=45",
    city: "Pune",
    locality: "Baner",
    kycStatus: "verified",
    lenderRating: 4.9,
    renterRating: 4.3,
    isPhoneVerified: true,
    roleTags: ["lender"],
  },
  {
    key: "renter_karan",
    name: "Karan Verma",
    phone: "9876501008",
    email: "karan.renter@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=21",
    city: "Delhi",
    locality: "Dwarka",
    kycStatus: "not_started",
    lenderRating: 4.1,
    renterRating: 4.4,
    isPhoneVerified: false,
    roleTags: ["renter"],
  },
  {
    key: "hybrid_isha",
    name: "Isha Malhotra",
    phone: "9876501009",
    email: "isha.hybrid@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=27",
    city: "Pune",
    locality: "Kothrud",
    kycStatus: "verified",
    lenderRating: 4.6,
    renterRating: 4.7,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
  {
    key: "lender_dev",
    name: "Dev Chawla",
    phone: "9876501010",
    email: "dev.lender@rentora.demo",
    profilePhoto: "https://i.pravatar.cc/300?img=62",
    city: "Bengaluru",
    locality: "Indiranagar",
    kycStatus: "failed",
    lenderRating: 4.2,
    renterRating: 4.1,
    isPhoneVerified: true,
    roleTags: ["lender"],
  },
];

export const listingTemplates: SeedListing[] = [
  {
    title: "Ergonomic Office Chair (Mesh + Lumbar Support)",
    category: "Furniture",
    subcategory: "Office chairs",
    description: "High-back ergonomic chair with adjustable armrests and lumbar support. Great for daily WFH use.",
    condition: "Like New",
    replacementValue: 18000,
    rentPrice: 950,
    rentUnit: "week",
    depositAmount: 4000,
    deliveryAvailable: true,
    rules: ["Indoor use only", "No tearing/stains", "Return cleaned"],
    accessories: ["Headrest", "Wheel lock attachments"],
  },
  {
    title: "Study Table for WFH Setup",
    category: "Furniture",
    subcategory: "Study/work tables",
    description: "Spacious engineered-wood table with cable-management tray for laptop/monitor setup.",
    condition: "Good",
    replacementValue: 14000,
    rentPrice: 1200,
    rentUnit: "month",
    depositAmount: 3500,
    deliveryAvailable: true,
    rules: ["No drilling or permanent modifications"],
    accessories: ["Cable tray", "Keyboard shelf"],
  },
  {
    title: "3-Seater Sofa (Fabric, Deep Comfort)",
    category: "Furniture",
    subcategory: "Sofas/recliners",
    description: "Comfortable 3-seater sofa ideal for short-term furnished stays and moving-in use cases.",
    condition: "Good",
    replacementValue: 42000,
    rentPrice: 2600,
    rentUnit: "month",
    depositAmount: 9000,
    deliveryAvailable: true,
    rules: ["No pets on sofa", "Avoid food spills"],
    accessories: ["2 cushion covers"],
  },
  {
    title: "Queen Bed with Storage",
    category: "Furniture",
    subcategory: "Beds/wardrobes",
    description: "Hydraulic storage queen bed frame for temporary home setups.",
    condition: "Good",
    replacementValue: 48000,
    rentPrice: 3200,
    rentUnit: "month",
    depositAmount: 12000,
    deliveryAvailable: true,
    rules: ["Mattress not included", "No structural modifications"],
    accessories: ["Toolkit for assembly"],
  },
  {
    title: "Recliner Lounge Chair",
    category: "Furniture",
    subcategory: "Sofas/recliners",
    description: "Single-seater premium recliner with adjustable comfort positions for living room setups.",
    condition: "Like New",
    replacementValue: 36000,
    rentPrice: 1900,
    rentUnit: "month",
    depositAmount: 8500,
    deliveryAvailable: true,
    rules: ["Avoid sharp objects near upholstery", "No outdoor use"],
    accessories: ["Removable head cushion"],
  },
  {
    title: "Canon 80D DSLR Camera Kit",
    category: "Cameras & Creator Gear",
    subcategory: "DSLR/mirrorless cameras",
    description: "Canon 80D with 18-135mm lens and backup battery. Ideal for event shoots and content projects.",
    condition: "Like New",
    replacementValue: 85000,
    rentPrice: 2100,
    rentUnit: "day",
    depositAmount: 18000,
    deliveryAvailable: false,
    rules: ["Share a valid ID before pickup", "No beach/water use"],
    accessories: ["Camera bag", "2 batteries", "64GB card"],
    specifications: { sensor: "APS-C", lens: "18-135mm" },
  },
  {
    title: "Sony Mirrorless Camera with Lens",
    category: "Cameras & Creator Gear",
    subcategory: "DSLR/mirrorless cameras",
    description: "Sony mirrorless body with prime lens for cinematic content and creator shoots.",
    condition: "Like New",
    replacementValue: 125000,
    rentPrice: 2800,
    rentUnit: "day",
    depositAmount: 25000,
    deliveryAvailable: true,
    rules: ["No dropping/impact damage", "Return with lens cap"],
    accessories: ["50mm lens", "Battery", "Charger"],
  },
  {
    title: "Sigma 24-70mm f/2.8 Lens",
    category: "Cameras & Creator Gear",
    subcategory: "Lenses",
    description: "Versatile creator lens for portrait and event work.",
    condition: "Good",
    replacementValue: 95000,
    rentPrice: 1500,
    rentUnit: "day",
    depositAmount: 22000,
    deliveryAvailable: false,
    rules: ["Use lens hood always outdoors"],
    accessories: ["Lens hood", "Protective pouch"],
  },
  {
    title: "Pro Carbon Tripod for Video",
    category: "Cameras & Creator Gear",
    subcategory: "Tripods",
    description: "Heavy-duty fluid head tripod for stable cinematic shots.",
    condition: "Like New",
    replacementValue: 26000,
    rentPrice: 550,
    rentUnit: "day",
    depositAmount: 6000,
    deliveryAvailable: true,
    rules: ["No sand/water exposure"],
    accessories: ["Carry case"],
  },
  {
    title: "Ring Light 18-inch with Stand",
    category: "Cameras & Creator Gear",
    subcategory: "Ring lights",
    description: "Bi-color ring light kit for live streams and beauty shoots.",
    condition: "Good",
    replacementValue: 8500,
    rentPrice: 300,
    rentUnit: "day",
    depositAmount: 2000,
    deliveryAvailable: true,
    rules: ["Indoor use only"],
    accessories: ["Phone holder", "Remote"],
  },
  {
    title: "DJI Gimbal for Mirrorless Cameras",
    category: "Cameras & Creator Gear",
    subcategory: "Gimbals",
    description: "3-axis stabilizer for smooth handheld shots and travel vlogs.",
    condition: "Like New",
    replacementValue: 39000,
    rentPrice: 900,
    rentUnit: "day",
    depositAmount: 8500,
    deliveryAvailable: true,
    rules: ["Balance camera before powering on"],
    accessories: ["Grip tripod", "USB-C cable"],
  },
  {
    title: "Wireless Lavalier Mic Duo Kit",
    category: "Cameras & Creator Gear",
    subcategory: "Wireless mics",
    description: "Dual transmitter wireless mic set for interviews and podcasts.",
    condition: "Good",
    replacementValue: 22000,
    rentPrice: 600,
    rentUnit: "day",
    depositAmount: 4500,
    deliveryAvailable: true,
    rules: ["Handle windshields carefully"],
    accessories: ["Receiver", "2 transmitters", "Windshields"],
  },
  {
    title: "PS5 Console with Controller",
    category: "Electronics & Gaming",
    subcategory: "Gaming consoles",
    description: "PlayStation 5 with one DualSense controller for weekend gaming sessions.",
    condition: "Like New",
    replacementValue: 54000,
    rentPrice: 1800,
    rentUnit: "week",
    depositAmount: 12000,
    deliveryAvailable: true,
    rules: ["No account sharing", "Return with all cables"],
    accessories: ["DualSense controller", "HDMI cable"],
  },
  {
    title: "Epson Projector for Movie Nights",
    category: "Electronics & Gaming",
    subcategory: "Projectors",
    description: "1080p home projector suitable for 100-inch indoor movie setups.",
    condition: "Good",
    replacementValue: 68000,
    rentPrice: 1400,
    rentUnit: "day",
    depositAmount: 15000,
    deliveryAvailable: true,
    rules: ["Do not move while lamp is hot"],
    accessories: ["Remote", "Power cable", "HDMI cable"],
  },
  {
    title: "JBL Party Speaker with Mic",
    category: "Electronics & Gaming",
    subcategory: "Party speakers",
    description: "High-output party speaker with wireless mic and light modes.",
    condition: "Good",
    replacementValue: 32000,
    rentPrice: 950,
    rentUnit: "day",
    depositAmount: 7000,
    deliveryAvailable: true,
    rules: ["No rain exposure", "Avoid max volume clipping"],
    accessories: ["Wireless mic", "Power cable"],
  },
  {
    title: "27-inch 4K Monitor",
    category: "Electronics & Gaming",
    subcategory: "Monitors",
    description: "Color-accurate UHD monitor for design, coding, and creator workflows.",
    condition: "Like New",
    replacementValue: 42000,
    rentPrice: 1700,
    rentUnit: "month",
    depositAmount: 10000,
    deliveryAvailable: false,
    rules: ["No dead-pixel claims after pickup"],
    accessories: ["Stand", "DisplayPort cable"],
  },
  {
    title: "Laser Printer for Office Use",
    category: "Electronics & Gaming",
    subcategory: "Printers",
    description: "Monochrome laser printer for temporary office setups and documentation work.",
    condition: "Good",
    replacementValue: 17000,
    rentPrice: 900,
    rentUnit: "month",
    depositAmount: 3500,
    deliveryAvailable: true,
    rules: ["Use compatible paper size only"],
    accessories: ["Starter toner"],
  },
  {
    title: "Xbox Series X with 2 Controllers",
    category: "Electronics & Gaming",
    subcategory: "Gaming consoles",
    description: "Series X bundle for co-op gaming weekends and tournaments.",
    condition: "Like New",
    replacementValue: 62000,
    rentPrice: 1900,
    rentUnit: "week",
    depositAmount: 13000,
    deliveryAvailable: true,
    rules: ["No account resale/modding"],
    accessories: ["2 controllers", "HDMI cable"],
  },
  {
    title: "Air Cooler for Monthly Rent",
    category: "Home Appliances",
    subcategory: "Air coolers",
    description: "Desert air cooler for hot summer months in medium-sized rooms.",
    condition: "Good",
    replacementValue: 13000,
    rentPrice: 1500,
    rentUnit: "month",
    depositAmount: 2500,
    deliveryAvailable: true,
    rules: ["Use clean water only", "Drain after use"],
    accessories: ["Remote", "Ice chamber tray"],
  },
  {
    title: "Premium Air Purifier (HEPA)",
    category: "Home Appliances",
    subcategory: "Air purifiers",
    description: "Smart purifier for indoor allergy control and cleaner air.",
    condition: "Like New",
    replacementValue: 29000,
    rentPrice: 1600,
    rentUnit: "month",
    depositAmount: 5000,
    deliveryAvailable: true,
    rules: ["Do not wash HEPA filter"],
    accessories: ["Filter set"],
  },
  {
    title: "Convection Microwave Oven",
    category: "Home Appliances",
    subcategory: "Microwaves",
    description: "Convection microwave with grill mode for short-term kitchen setups.",
    condition: "Good",
    replacementValue: 22000,
    rentPrice: 1400,
    rentUnit: "month",
    depositAmount: 4500,
    deliveryAvailable: true,
    rules: ["No metal utensils"],
    accessories: ["Grill rack", "Turntable"],
  },
  {
    title: "Vacuum Cleaner",
    category: "Home Appliances",
    subcategory: "Vacuum cleaners",
    description: "Bagless vacuum cleaner for home deep-clean and move-out cleanup.",
    condition: "Good",
    replacementValue: 12000,
    rentPrice: 500,
    rentUnit: "day",
    depositAmount: 2500,
    deliveryAvailable: true,
    rules: ["No wet floor vacuuming"],
    accessories: ["Crevice nozzle", "Brush head"],
  },
  {
    title: "Mini Fridge for Studio Apartment",
    category: "Home Appliances",
    subcategory: "Mini fridges",
    description: "Compact mini fridge useful for short-term stays and office pantries.",
    condition: "Good",
    replacementValue: 18000,
    rentPrice: 1700,
    rentUnit: "month",
    depositAmount: 6000,
    deliveryAvailable: true,
    rules: ["Keep upright during transport"],
    accessories: ["Power cord"],
  },
  {
    title: "Robot Vacuum Cleaner",
    category: "Home Appliances",
    subcategory: "Vacuum cleaners",
    description: "Auto-cleaning robot vacuum for daily maintenance cleaning.",
    condition: "Like New",
    replacementValue: 34000,
    rentPrice: 2200,
    rentUnit: "month",
    depositAmount: 9000,
    deliveryAvailable: false,
    rules: ["Use only indoor smooth surfaces"],
    accessories: ["Docking station", "Extra brush"],
  },
  {
    title: "Bosch Drill Machine",
    category: "Tools & DIY",
    subcategory: "Drill machines",
    description: "Impact drill for furniture mounting and wall installation tasks.",
    condition: "Good",
    replacementValue: 11000,
    rentPrice: 450,
    rentUnit: "day",
    depositAmount: 2500,
    deliveryAvailable: true,
    rules: ["Use safety gloves and goggles"],
    accessories: ["Drill bits set"],
  },
  {
    title: "Foldable Ladder (12 ft)",
    category: "Tools & DIY",
    subcategory: "Ladders",
    description: "Aluminum foldable ladder suitable for maintenance and painting tasks.",
    condition: "Good",
    replacementValue: 9500,
    rentPrice: 350,
    rentUnit: "day",
    depositAmount: 1800,
    deliveryAvailable: true,
    rules: ["Use on flat surfaces only"],
    accessories: ["Anti-slip pads"],
  },
  {
    title: "Pressure Washer for Deep Cleaning",
    category: "Tools & DIY",
    subcategory: "Pressure washers",
    description: "High-pressure washer for balcony, driveway, and vehicle cleaning.",
    condition: "Like New",
    replacementValue: 26000,
    rentPrice: 700,
    rentUnit: "day",
    depositAmount: 5500,
    deliveryAvailable: true,
    rules: ["No dry running", "Avoid direct electrical spray"],
    accessories: ["Nozzle kit", "Hose"],
  },
  {
    title: "Professional Tool Kit (125 pcs)",
    category: "Tools & DIY",
    subcategory: "Tool kits",
    description: "Comprehensive hand tool kit for DIY fixes and furniture assembly.",
    condition: "Good",
    replacementValue: 15000,
    rentPrice: 550,
    rentUnit: "week",
    depositAmount: 3000,
    deliveryAvailable: true,
    rules: ["Return full kit with all pieces"],
    accessories: ["Hard case"],
  },
  {
    title: "Rotary Hammer Drill",
    category: "Tools & DIY",
    subcategory: "Drill machines",
    description: "Rotary hammer for concrete drilling and heavy-duty wall work.",
    condition: "Good",
    replacementValue: 24000,
    rentPrice: 850,
    rentUnit: "day",
    depositAmount: 6000,
    deliveryAvailable: false,
    rules: ["Use ear protection"],
    accessories: ["SDS bits set", "Carry case"],
  },
  {
    title: "Painter Scaffold Ladder Combo",
    category: "Tools & DIY",
    subcategory: "Ladders",
    description: "Multi-position ladder scaffold combo for home renovation projects.",
    condition: "Like New",
    replacementValue: 30000,
    rentPrice: 1200,
    rentUnit: "week",
    depositAmount: 8000,
    deliveryAvailable: true,
    rules: ["Assembly required before use"],
    accessories: ["Stabilizer bars"],
  },
  {
    title: "Projector Screen (120 inch)",
    category: "Events & Outdoor",
    subcategory: "Projector screens",
    description: "Portable 120-inch screen suitable for events and rooftop movie nights.",
    condition: "Like New",
    replacementValue: 18000,
    rentPrice: 700,
    rentUnit: "day",
    depositAmount: 3500,
    deliveryAvailable: true,
    rules: ["Avoid use in heavy wind"],
    accessories: ["Tripod stand", "Carry bag"],
  },
  {
    title: "Event Foldable Tables and Chairs Set",
    category: "Events & Outdoor",
    subcategory: "Foldable tables/chairs",
    description: "Bulk foldable furniture set for small events, popups, and gatherings.",
    condition: "Good",
    replacementValue: 46000,
    rentPrice: 2900,
    rentUnit: "day",
    depositAmount: 10000,
    deliveryAvailable: true,
    rules: ["Return after dry cleaning wipe-down"],
    accessories: ["Transport straps"],
  },
  {
    title: "Camping Tent for 4 People",
    category: "Events & Outdoor",
    subcategory: "Camping tents",
    description: "All-weather 4-person camping tent with rainfly and ventilation mesh.",
    condition: "Good",
    replacementValue: 22000,
    rentPrice: 1000,
    rentUnit: "day",
    depositAmount: 4500,
    deliveryAvailable: true,
    rules: ["Dry before packing", "No open flame nearby"],
    accessories: ["Groundsheet", "Pegs"],
  },
  {
    title: "Large Travel Suitcase (105L)",
    category: "Events & Outdoor",
    subcategory: "Large suitcases",
    description: "Hard-shell large suitcase for relocation and long trips.",
    condition: "Like New",
    replacementValue: 14000,
    rentPrice: 500,
    rentUnit: "week",
    depositAmount: 2000,
    deliveryAvailable: true,
    rules: ["No over-stuffing beyond zip limit"],
    accessories: ["TSA lock"],
  },
  {
    title: "70L Trekking Backpack",
    category: "Events & Outdoor",
    subcategory: "Trekking bags",
    description: "Large trekking backpack with frame support and rain cover.",
    condition: "Good",
    replacementValue: 12000,
    rentPrice: 450,
    rentUnit: "week",
    depositAmount: 2500,
    deliveryAvailable: true,
    rules: ["Do not wash in machine"],
    accessories: ["Rain cover"],
  },
  {
    title: "Outdoor Gazebo Canopy Tent",
    category: "Events & Outdoor",
    subcategory: "Camping tents",
    description: "Pop-up canopy tent ideal for outdoor gatherings and food stalls.",
    condition: "Good",
    replacementValue: 28000,
    rentPrice: 1200,
    rentUnit: "day",
    depositAmount: 6500,
    deliveryAvailable: true,
    rules: ["Secure with weights during use"],
    accessories: ["Side walls", "Weight bags"],
  },
];

const unsplash = (photoId: string) =>
  `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=1400&q=80`;

export const listingImageCatalog: Record<
  string,
  { imageQuery: string; photos: string[] }
> = {
  "Ergonomic Office Chair (Mesh + Lumbar Support)": {
    imageQuery: "ergonomic office chair",
    photos: [unsplash("photo-1688578735427-994ecdea3ea4"), unsplash("photo-1688578735352-9a6f2ac3b70a")],
  },
  "Study Table for WFH Setup": {
    imageQuery: "study work table desk",
    photos: [unsplash("photo-1650661926447-9efb2610f64c"), unsplash("photo-1616400619175-5beda3a17896")],
  },
  "3-Seater Sofa (Fabric, Deep Comfort)": {
    imageQuery: "3 seater sofa living room",
    photos: [unsplash("photo-1555041469-a586c61ea9bc"), unsplash("photo-1634712282287-14ed57b9cc89")],
  },
  "Queen Bed with Storage": {
    imageQuery: "queen bed furniture",
    photos: [unsplash("photo-1505693416388-ac5ce068fe85"), unsplash("photo-1522771739844-6a9f6d5f14af")],
  },
  "Recliner Lounge Chair": {
    imageQuery: "recliner lounge chair",
    photos: [unsplash("photo-1567016432779-094069958ea5"), unsplash("photo-1512212621149-107ffe572d2f")],
  },
  "Canon 80D DSLR Camera Kit": {
    imageQuery: "canon 80d dslr camera kit",
    photos: [unsplash("photo-1616423640778-28d1b53229bd"), unsplash("photo-1546805022-9c4e4ab7e3a3")],
  },
  "Sony Mirrorless Camera with Lens": {
    imageQuery: "sony mirrorless camera lens",
    photos: [unsplash("photo-1598469701566-59655353deb4"), unsplash("photo-1593449651424-adb56e5001aa")],
  },
  "Sigma 24-70mm f/2.8 Lens": {
    imageQuery: "camera lens 24-70",
    photos: [unsplash("photo-1516035069371-29a1b244cc32"), unsplash("photo-1582994254571-52c62d96ebab")],
  },
  "Pro Carbon Tripod for Video": {
    imageQuery: "camera tripod video",
    photos: [unsplash("photo-1576299090369-9067e4adca28"), unsplash("photo-1594147216879-97803adfb44d")],
  },
  "Ring Light 18-inch with Stand": {
    imageQuery: "ring light stand photography",
    photos: [unsplash("photo-1673196649671-eb09066ad6c1"), unsplash("photo-1478826160983-e6db8c7d537a")],
  },
  "DJI Gimbal for Mirrorless Cameras": {
    imageQuery: "camera gimbal stabilizer",
    photos: [unsplash("photo-1602781975605-a032a4234333"), unsplash("photo-1589800891835-e2bd625c2caa")],
  },
  "Wireless Lavalier Mic Duo Kit": {
    imageQuery: "wireless lavalier microphone kit",
    photos: [unsplash("photo-1521424159246-e4a66f267e4b"), unsplash("photo-1581548708095-7158f2e63857")],
  },
  "PS5 Console with Controller": {
    imageQuery: "ps5 console controller",
    photos: [unsplash("photo-1607853202273-797f1c22a38e"), unsplash("photo-1672772685267-04b983099b1b")],
  },
  "Epson Projector for Movie Nights": {
    imageQuery: "home projector movie night",
    photos: [unsplash("photo-1535016120720-40c646be5580"), unsplash("photo-1579036095242-fe07594274ca")],
  },
  "JBL Party Speaker with Mic": {
    imageQuery: "party speaker with microphone",
    photos: [unsplash("photo-1633431577706-595c31e64d50"), unsplash("photo-1610560574613-39a29288748c")],
  },
  "27-inch 4K Monitor": {
    imageQuery: "4k computer monitor desk",
    photos: [unsplash("photo-1611648694931-1aeda329f9da"), unsplash("photo-1579765754037-5bfef757251a")],
  },
  "Laser Printer for Office Use": {
    imageQuery: "laser printer office",
    photos: [unsplash("photo-1612815154858-60aa4c59eaa6"), unsplash("photo-1706895040634-62055892cbbb")],
  },
  "Xbox Series X with 2 Controllers": {
    imageQuery: "xbox series x console controller",
    photos: [unsplash("photo-1709587797077-7a2c94411514"), unsplash("photo-1709587797203-b28ef0e16e31")],
  },
  "Air Cooler for Monthly Rent": {
    imageQuery: "air cooler appliance",
    photos: [unsplash("photo-1713874990887-6e76a16a2884"), unsplash("photo-1658671227304-9a989a842c88")],
  },
  "Premium Air Purifier (HEPA)": {
    imageQuery: "air purifier home appliance",
    photos: [unsplash("photo-1632928274371-878938e4d825"), unsplash("photo-1652352529254-5106f4c8e03c")],
  },
  "Convection Microwave Oven": {
    imageQuery: "convection microwave oven kitchen",
    photos: [unsplash("photo-1690731849383-514935755156"), unsplash("photo-1585659722983-3a675dabf23d")],
  },
  "Vacuum Cleaner": {
    imageQuery: "vacuum cleaner home",
    photos: [unsplash("photo-1722710070534-e31f0290d8de"), unsplash("photo-1527515637462-cff94eecc1ac")],
  },
  "Mini Fridge for Studio Apartment": {
    imageQuery: "mini fridge appliance",
    photos: [unsplash("photo-1540961403310-79825242906e"), unsplash("photo-1542331325-bebfc9b990d7")],
  },
  "Robot Vacuum Cleaner": {
    imageQuery: "robot vacuum cleaner",
    photos: [unsplash("photo-1686178827149-6d55c72d81df"), unsplash("photo-1569698134101-f15cde5cd66c")],
  },
  "Bosch Drill Machine": {
    imageQuery: "bosch drill machine",
    photos: [unsplash("photo-1603138519910-9a3813cc0ca6"), unsplash("photo-1687920810115-921c06661914")],
  },
  "Foldable Ladder (12 ft)": {
    imageQuery: "foldable ladder",
    photos: [unsplash("photo-1570050785780-3c79854c7813"), unsplash("photo-1658669742598-2f70354c3326")],
  },
  "Pressure Washer for Deep Cleaning": {
    imageQuery: "pressure washer cleaning",
    photos: [unsplash("photo-1592365559101-19adfefdf294"), unsplash("photo-1718152423993-a29048dbc223")],
  },
  "Professional Tool Kit (125 pcs)": {
    imageQuery: "professional tool kit",
    photos: [unsplash("photo-1426927308491-6380b6a9936f"), unsplash("photo-1567361808960-dec9cb578182")],
  },
  "Rotary Hammer Drill": {
    imageQuery: "rotary hammer drill",
    photos: [unsplash("photo-1684564577719-1e9944866a45"), unsplash("photo-1613790410526-0c15af6a250c")],
  },
  "Painter Scaffold Ladder Combo": {
    imageQuery: "scaffold ladder combo",
    photos: [unsplash("photo-1583347262296-9282fea2701e"), unsplash("photo-1556009756-5a06dce4729d")],
  },
  "Projector Screen (120 inch)": {
    imageQuery: "projector screen portable",
    photos: [unsplash("photo-1694253987646-353954f1889d"), unsplash("photo-1560439514-0fc9d2cd5e1b")],
  },
  "Event Foldable Tables and Chairs Set": {
    imageQuery: "event foldable tables chairs",
    photos: [unsplash("photo-1758960626443-ec4cd88cdbf8"), unsplash("photo-1708920326687-2585f79eb00d")],
  },
  "Camping Tent for 4 People": {
    imageQuery: "camping tent 4 people",
    photos: [unsplash("photo-1624923686627-514dd5e57bae"), unsplash("photo-1537905569824-f89f14cceb68")],
  },
  "Large Travel Suitcase (105L)": {
    imageQuery: "large travel suitcase",
    photos: [unsplash("photo-1670888664952-efff442ec0d2"), unsplash("photo-1502301197179-65228ab57f78")],
  },
  "70L Trekking Backpack": {
    imageQuery: "70L trekking backpack",
    photos: [unsplash("photo-1622260614153-03223fb72052"), unsplash("photo-1499803270242-467f7311582d")],
  },
  "Outdoor Gazebo Canopy Tent": {
    imageQuery: "outdoor gazebo canopy tent",
    photos: [unsplash("photo-1711747708333-233f76d30cd8"), unsplash("photo-1628451035238-ca4c2ee37009")],
  },
};

export const requestStatusSeed: RequestStatus[] = [
  "requested",
  "chatting",
  "accepted",
  "active",
  "return_pending",
  "completed",
  "rejected",
  "cancelled",
  "accepted",
  "chatting",
  "requested",
  "completed",
  "active",
  "return_pending",
];
