export interface SeedUser {
  key: string;
  name: string;
  phone: string;
  email: string;
  password: string;
  profilePhoto: string;
  city: string;
  locality: string;
  kycStatus: "not_started" | "pending" | "verified" | "failed";
  lenderRating: number;
  renterRating: number;
  isPhoneVerified: boolean;
  roleTags: string[];
}

export interface SeedListing {
  title: string;
  category: string;
  subcategory: string;
  description: string;
  condition: string;
  replacementValue: number;
  rentPrice: number;
  rentUnit: "day" | "week" | "month";
  depositAmount: number;
  deliveryAvailable: boolean;
  rules: string[];
  accessories: string[];
  specifications?: Record<string, string | number>;
  photos?: string[];
  imageQuery?: string;
}

export const seedUsers: SeedUser[] = [
  {
    key: "kunal",
    name: "Kunal",
    phone: "9876501001",
    email: "Kunal.rohilla@codibex.com",
    password: "Kunal@123",
    profilePhoto: "https://randomuser.me/api/portraits/men/32.jpg",
    city: "Bengaluru",
    locality: "Indiranagar",
    kycStatus: "verified",
    lenderRating: 4.9,
    renterRating: 4.8,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
  {
    key: "aryan",
    name: "Aryan",
    phone: "9876501002",
    email: "Aryan.maurya@codibex.com",
    password: "Aryan@123",
    profilePhoto: "https://randomuser.me/api/portraits/men/75.jpg",
    city: "Bengaluru",
    locality: "HSR Layout",
    kycStatus: "verified",
    lenderRating: 4.8,
    renterRating: 4.7,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
  {
    key: "tanisha",
    name: "Tanisha",
    phone: "9876501003",
    email: "tanisha.sahni@codibex.com",
    password: "Tanisha@123",
    profilePhoto: "https://randomuser.me/api/portraits/women/44.jpg",
    city: "Bengaluru",
    locality: "Koramangala",
    kycStatus: "verified",
    lenderRating: 4.9,
    renterRating: 4.8,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
  {
    key: "deepanshu",
    name: "Deepanshu",
    phone: "9876501004",
    email: "Deepanshu.sati@codibex.com",
    password: "Deepanshu@123",
    profilePhoto: "https://randomuser.me/api/portraits/men/12.jpg",
    city: "Bengaluru",
    locality: "Indiranagar",
    kycStatus: "verified",
    lenderRating: 4.7,
    renterRating: 4.8,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
  {
    key: "samiksha",
    name: "Samiksha",
    phone: "9876501005",
    email: "samiksha.singh@codibex.com",
    password: "Samiksha@123",
    profilePhoto: "https://randomuser.me/api/portraits/women/65.jpg",
    city: "Bengaluru",
    locality: "HSR Layout",
    kycStatus: "verified",
    lenderRating: 4.8,
    renterRating: 4.9,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
  {
    key: "akanksha",
    name: "Akanksha",
    phone: "9876501006",
    email: "Akanksha.pandey@codibex.com",
    password: "Akanksha@123",
    profilePhoto: "https://randomuser.me/api/portraits/women/28.jpg",
    city: "Bengaluru",
    locality: "Koramangala",
    kycStatus: "verified",
    lenderRating: 4.9,
    renterRating: 4.7,
    isPhoneVerified: true,
    roleTags: ["hybrid"],
  },
];

export const listingTemplates: SeedListing[] = [
  {
    title: "Portable Standing Desk Converter",
    category: "Furniture",
    subcategory: "Study/work tables",
    description: "Adjustable sit-stand desk riser for a temporary ergonomic work setup.",
    condition: "Like New",
    replacementValue: 18000,
    rentPrice: 700,
    rentUnit: "week",
    depositAmount: 3500,
    deliveryAvailable: true,
    rules: ["Indoor use only", "Do not overload the lift tray"],
    accessories: ["Keyboard tray", "Allen key"],
    imageQuery: "standing desk converter",
  },
  {
    title: "MacBook Pro M2 Creator Laptop",
    category: "Electronics & Gaming",
    subcategory: "Laptops",
    description: "M2 laptop suitable for short editing sprints, demos, and travel work.",
    condition: "Like New",
    replacementValue: 145000,
    rentPrice: 3200,
    rentUnit: "day",
    depositAmount: 30000,
    deliveryAvailable: false,
    rules: ["No OS reinstall", "Return with charger and sleeve"],
    accessories: ["USB-C charger", "Protective sleeve"],
    specifications: { memory: "16GB", storage: "512GB" },
    imageQuery: "macbook pro laptop desk",
  },
  {
    title: "GoPro HERO Action Camera Kit",
    category: "Cameras & Creator Gear",
    subcategory: "Action cameras",
    description: "Compact action camera kit for travel reels, sports shots, and POV footage.",
    condition: "Good",
    replacementValue: 42000,
    rentPrice: 1200,
    rentUnit: "day",
    depositAmount: 10000,
    deliveryAvailable: true,
    rules: ["Use waterproof case near water", "Return all mounts"],
    accessories: ["Waterproof case", "Chest mount", "Two batteries"],
    specifications: { resolution: "5.3K", stabilization: "HyperSmooth" },
    imageQuery: "gopro action camera kit",
  },
  {
    title: "Nintendo Switch OLED Bundle",
    category: "Electronics & Gaming",
    subcategory: "Gaming consoles",
    description: "Switch OLED bundle for family game nights and weekend tournaments.",
    condition: "Like New",
    replacementValue: 39000,
    rentPrice: 1500,
    rentUnit: "week",
    depositAmount: 9000,
    deliveryAvailable: true,
    rules: ["No account purchases", "Keep screen protector intact"],
    accessories: ["Dock", "Joy-Con pair", "HDMI cable"],
    imageQuery: "nintendo switch oled console",
  },
  {
    title: "Portable Garment Steamer",
    category: "Home Appliances",
    subcategory: "Garment steamers",
    description: "Handheld steamer for events, interviews, shoots, and quick wardrobe prep.",
    condition: "Good",
    replacementValue: 7500,
    rentPrice: 350,
    rentUnit: "day",
    depositAmount: 1500,
    deliveryAvailable: true,
    rules: ["Use clean water only", "Empty tank before return"],
    accessories: ["Fabric brush", "Travel pouch"],
    imageQuery: "portable garment steamer",
  },
  {
    title: "Adjustable Baby High Chair",
    category: "Furniture",
    subcategory: "Kids furniture",
    description: "Clean adjustable high chair for visiting families and short stays.",
    condition: "Like New",
    replacementValue: 12000,
    rentPrice: 800,
    rentUnit: "week",
    depositAmount: 2500,
    deliveryAvailable: true,
    rules: ["Return wiped down", "Use harness during seating"],
    accessories: ["Tray", "Safety harness"],
    imageQuery: "baby high chair",
  },
  {
    title: "Cordless Grass Trimmer",
    category: "Tools & DIY",
    subcategory: "Garden tools",
    description: "Battery-powered trimmer for balcony gardens, lawns, and quick cleanups.",
    condition: "Good",
    replacementValue: 16000,
    rentPrice: 650,
    rentUnit: "day",
    depositAmount: 3500,
    deliveryAvailable: true,
    rules: ["Wear eye protection", "Return battery charged"],
    accessories: ["Battery pack", "Charger", "Extra spool"],
    imageQuery: "cordless grass trimmer",
  },
  {
    title: "Manual Tile Cutter",
    category: "Tools & DIY",
    subcategory: "Tile cutters",
    description: "Manual ceramic tile cutter for kitchen, bathroom, and repair work.",
    condition: "Good",
    replacementValue: 14000,
    rentPrice: 550,
    rentUnit: "day",
    depositAmount: 3000,
    deliveryAvailable: false,
    rules: ["Use gloves", "Clean guide rails before return"],
    accessories: ["Measuring guide", "Carry case"],
    imageQuery: "manual tile cutter tool",
  },
  {
    title: "Espresso Coffee Machine",
    category: "Home Appliances",
    subcategory: "Coffee machines",
    description: "Compact espresso machine for popups, house parties, and trial use.",
    condition: "Like New",
    replacementValue: 36000,
    rentPrice: 1300,
    rentUnit: "day",
    depositAmount: 8500,
    deliveryAvailable: true,
    rules: ["Use filtered water", "Return cleaned and descaled"],
    accessories: ["Portafilter", "Milk frothing pitcher"],
    imageQuery: "espresso coffee machine",
  },
  {
    title: "Portable Photo Studio Light Box",
    category: "Cameras & Creator Gear",
    subcategory: "Lighting",
    description: "Foldable light box for product shoots, catalog photos, and creator work.",
    condition: "Like New",
    replacementValue: 11500,
    rentPrice: 450,
    rentUnit: "day",
    depositAmount: 2500,
    deliveryAvailable: true,
    rules: ["Fold only along marked creases", "Keep backdrops clean"],
    accessories: ["White backdrop", "Black backdrop", "Power adapter"],
    imageQuery: "portable photo studio light box",
  },
  {
    title: "Foldable Wheelchair",
    category: "Events & Outdoor",
    subcategory: "Mobility aids",
    description: "Lightweight foldable wheelchair for guests, travel, and short recovery periods.",
    condition: "Good",
    replacementValue: 22000,
    rentPrice: 1100,
    rentUnit: "week",
    depositAmount: 5000,
    deliveryAvailable: true,
    rules: ["Use brakes while stationary", "Return cleaned"],
    accessories: ["Seat cushion", "Foot rests"],
    imageQuery: "foldable wheelchair",
  },
  {
    title: "Karaoke Mixer and Mic Set",
    category: "Electronics & Gaming",
    subcategory: "Audio mixers",
    description: "Compact karaoke mixer with two wireless microphones for parties and events.",
    condition: "Good",
    replacementValue: 24000,
    rentPrice: 1000,
    rentUnit: "day",
    depositAmount: 5500,
    deliveryAvailable: true,
    rules: ["No outdoor rain exposure", "Return with charged microphones"],
    accessories: ["Two wireless mics", "Mixer", "Audio cables"],
    imageQuery: "karaoke mixer wireless microphones",
  },
];

export const listingImageCatalog: Record<
  string,
  { imageQuery: string; photos: string[] }
> = {};
